package main

import (
	"github.com/aws/aws-sdk-go/aws/session"
	SecurityHub "github.com/aws/aws-sdk-go/service/securityhub"

	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"strings"
	"time"
)

type ScanResult struct {
	Profiles []Profile `json:"profiles"`
}

type Tag struct {
	Severity  string `json:"severity"`
	Cis_id    string `json:"cis_id"`
	Cis_level int    `json:"cis_level"`
	Check     string `json:"check"`
	Fix       string `json:"fix"`
}

type Profile struct {
	Name       string    `json:"name"`
	Maintainer string    `json:"maintainer"`
	Summary    string    `json:"summary"`
	License    string    `json:"license"`
	Controls   []Control `json:"controls"`
}

type Control struct {
	Id    string `json:"id"`
	Title string `json:"title"`
	Desc  string `json:"desc"`
	Tags  Tag    `json:"tags"`
}

// severityToCriticality expects a string with severity and returns a int representation of it.
//    * 0 - INFORMATIONAL
//
//    * 1–39 - LOW
//
//    * 40–69 - MEDIUM
//
//    * 70–89 - HIGH
//
//    * 90–100 - CRITICAL
func severityToCriticality(severity string) int64 {
	switch strings.ToLower(severity) {
	case "informational":
		return 0
	case "low":
		return 39
	case "medium":
		return 69
	case "high":
		return 89
	case "critical":
		return 100
	default:
		return 0
	}
}

func truncateString(val string, maxLength int) string {
	if len(val) > maxLength {
		trimmedVal := val[0:maxLength]
		return trimmedVal
	}
	return val
}

// GenerateSecurityHubFinding expects a inspec json object and returns a new security hub finding.
func GenerateSecurityHubFinding(control Control, profile Profile, accountId, arn, rdsARN string) (SecurityHub.AwsSecurityFinding, error) {
	var SecurityHubGenerator = "cms-ars-3.1-moderate-aws-rds-oracle-mysql-ee-5.7-cis-overlay"
	var ResourceType = "RDS MYSQL Instance"
	var Resource = SecurityHub.Resource{
		Id:   &rdsARN,
		Type: &ResourceType,
	}
	var ResourceList []*SecurityHub.Resource
	var schemaVersion = "2018-10-08"
	var record SecurityHub.AwsSecurityFinding
	criticality := severityToCriticality(control.Tags.Severity)
	timeStamp := time.Now().UTC().Format("2006-01-02T15:04:05Z07:00")
	findingStatus := "ACTIVE"
	ResourceList = append(ResourceList, &Resource)
	remediationText := truncateString(control.Tags.Fix, 511)
	var findingTypes []*string
	findingTypeStr := "Software and Configuration Checks/Vulnerabilities/CVE for RDS MYSQL"
	severityLabel := strings.ToUpper(control.Tags.Severity)
	findingTypes = append(findingTypes, &findingTypeStr)
	providerFields := SecurityHub.FindingProviderFields{
		Confidence:  &criticality,
		Criticality: &criticality,
		Severity: &SecurityHub.FindingProviderSeverity{
			Label: &severityLabel,
		},
		Types: findingTypes,
	}

	record.AwsAccountId = &accountId
	record.CreatedAt = &timeStamp
	record.Description = &control.Desc
	record.FindingProviderFields = &providerFields
	record.GeneratorId = &SecurityHubGenerator
	record.Id = &control.Id
	// The ARN generated by Security Hub that uniquely identifies a product that
	// generates findings. This can be the ARN for a third-party product that is
	// integrated with Security Hub, or the ARN for a custom integration.
	record.ProductArn = &arn
	// A set of resource data types that describe the resources that the finding
	// refers to.
	record.Resources = ResourceList
	record.SchemaVersion = &schemaVersion
	//record.Types		 = *["Software and Configuration Checks/Vulnerabilities/CVE with InSpec profile"]
	record.RecordState = &findingStatus
	record.Severity = &SecurityHub.Severity{
		Label: &severityLabel,
	}
	record.Title = &control.Title
	record.Types = findingTypes
	record.UpdatedAt = &timeStamp
	record.Criticality = &criticality
	record.Remediation = &SecurityHub.Remediation{
		Recommendation: &SecurityHub.Recommendation{
			Text: &remediationText,
		},
	}
	return record, nil
}

func ProcessFindingsIntoSecurityHub(profiles []Profile, isDryRun bool, accountId, arn, rdsARN string) error {
	var findings []*SecurityHub.AwsSecurityFinding

	for _, profile := range profiles {
		for _, control := range profile.Controls {
			// convert inspec finding into security hub finding
			finding, err := GenerateSecurityHubFinding(control, profile, accountId, arn, rdsARN)
			if err != nil {
				return err
			}
			findings = append(findings, &finding)
		}
	}

	if !isDryRun {
		// https://docs.aws.amazon.com/sdk-for-go/api/aws/session/
		// Create new session and assume the role of ECS task runner
		// By default the SDK will only load the shared credentials file's (~/.aws/credentials) credentials values,
		// and all other config is provided by the environment variables, SDK defaults, and user provided aws.Config values.

		// If the AWS_SDK_LOAD_CONFIG environment variable is set,
		// or SharedConfigEnable option is used to create the Session the full shared config values will be loaded.
		sess, err := session.NewSessionWithOptions(session.Options{
			SharedConfigState: session.SharedConfigEnable,
		})
		if err != nil {
			return err
		}

		hub := SecurityHub.New(sess)
		batchFindings := &SecurityHub.BatchImportFindingsInput{
			Findings: findings,
		}
		out, importError := hub.BatchImportFindings(batchFindings)
		if importError != nil {
			return importError
		}
		fmt.Println(out)
	} else {
		for _, find := range findings {
			fmt.Println(find)
		}
	}
	return nil
}

func main() {
	// read flag values
	isDryRun := flag.Bool("dry", true, "Dry run, without uploading findings into security hub")
	accountId := flag.String("accountid", "", "The AWS account ID that a finding is generated in")
	// The ARN generated by Security Hub that uniquely identifies a product that
	// generates findings. This can be the ARN for a third-party product that is
	// integrated with Security Hub, or the ARN for a custom integration.
	arn := flag.String("product-arn", "", "ARN for this custom integration")
	rdsARN:= flag.String("rds-arn", "", "ARN of the RDS instance scanned")

	flag.Parse()

	var result ScanResult
	dec := json.NewDecoder(os.Stdin)
	for {
		err := dec.Decode(&result)
		if err != nil {
			if err == io.EOF {
				break // reached end of file, exit loop
			}
			log.Fatal("failed to parse json stream", err)
		}
	}
	err := ProcessFindingsIntoSecurityHub(result.Profiles, *isDryRun, *accountId, *arn, *rdsARN)
	if err != nil {
		log.Fatal("failed to process findings", err)
	}
}